import { InsertSpell } from "@shared/schema";

export const SRD_SPELLS: Omit<InsertSpell, "id">[] = [
  // CANTRIPS (Level 0)
  {
    name: "Fire Bolt",
    level: 0,
    school: "evocation",
    castingTime: "1 action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn't being worn or carried. This spell's damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).",
    classes: ["sorcerer", "wizard"],
    damageType: "fire",
    damageDice: "1d10",
    srdCompliant: true,
  },
  {
    name: "Ray of Frost",
    level: 0,
    school: "evocation",
    castingTime: "1 action",
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "A frigid beam of blue-white light streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, it takes 1d8 cold damage, and its speed is reduced by 10 feet until the start of your next turn. The spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).",
    classes: ["sorcerer", "wizard"],
    damageType: "cold",
    damageDice: "1d8",
    srdCompliant: true,
  },
  {
    name: "Shocking Grasp",
    level: 0,
    school: "evocation",
    castingTime: "1 action",
    range: "Touch",
    components: "V, S",
    duration: "Instantaneous",
    description: "Lightning springs from your hand to deliver a shock to a creature you try to touch. Make a melee spell attack against the target. You have advantage on the attack roll if the target is wearing armor made of metal. On a hit, the target takes 1d8 lightning damage, and it can't take reactions until the start of its next turn.",
    classes: ["sorcerer", "wizard"],
    damageType: "lightning",
    damageDice: "1d8",
    srdCompliant: true,
  },
  {
    name: "Light",
    level: 0,
    school: "evocation",
    castingTime: "1 action",
    range: "Touch",
    components: "V, M (a firefly or phosphorescent moss)",
    duration: "1 hour",
    description: "You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light in a 20-foot radius and dim light for an additional 20 feet. The light can be colored as you like. Completely covering the object with something opaque blocks the light. The spell ends if you cast it again or dismiss it as an action.",
    classes: ["bard", "cleric", "sorcerer", "wizard"],
    srdCompliant: true,
  },
  {
    name: "Mage Hand",
    level: 0,
    school: "conjuration",
    castingTime: "1 action",
    range: "30 feet",
    components: "V, S",
    duration: "1 minute",
    description: "A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it as an action. The hand vanishes if it is ever more than 30 feet away from you or if you cast this spell again. You can use your action to control the hand. You can use the hand to manipulate an object, open an unlocked door or container, stow or retrieve an item from an open container, or pour the contents out of a vial. You can move the hand up to 30 feet each time you use it. The hand can't attack, activate magic items, or carry more than 10 pounds.",
    classes: ["bard", "sorcerer", "warlock", "wizard"],
    srdCompliant: true,
  },
  {
    name: "Prestidigitation",
    level: 0,
    school: "transmutation",
    castingTime: "1 action",
    range: "10 feet",
    components: "V, S",
    duration: "Up to 1 hour",
    description: "This spell is a minor magical trick that novice spellcasters use for practice. You create one of the following magical effects within range: You create an instantaneous, harmless sensory effect, such as a shower of sparks, a puff of wind, faint musical notes, or an odd odor. You instantaneously light or snuff out a candle, a torch, or a small campfire. You instantaneously clean or soil an object no larger than 1 cubic foot. You chill, warm, or flavor up to 1 cubic foot of nonliving material for 1 hour. You make a color, a small mark, or a symbol appear on an object or a surface for 1 hour. You create a nonmagical trinket or an illusory image that can fit in your hand and that lasts until the end of your next turn.",
    classes: ["bard", "sorcerer", "warlock", "wizard"],
    srdCompliant: true,
  },
  {
    name: "Sacred Flame",
    level: 0,
    school: "evocation",
    castingTime: "1 action",
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "Flame-like radiance descends on a creature that you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 radiant damage. The target gains no benefit from cover for this saving throw. The spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).",
    classes: ["cleric"],
    damageType: "radiant",
    damageDice: "1d8",
    savingThrow: "DEX",
    srdCompliant: true,
  },
  {
    name: "Guidance",
    level: 0,
    school: "divination",
    castingTime: "1 action",
    range: "Touch",
    components: "V, S",
    duration: "Concentration, up to 1 minute",
    description: "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends.",
    classes: ["cleric", "druid"],
    concentration: true,
    srdCompliant: true,
  },
  {
    name: "Thaumaturgy",
    level: 0,
    school: "transmutation",
    castingTime: "1 action",
    range: "30 feet",
    components: "V",
    duration: "Up to 1 minute",
    description: "You manifest a minor wonder, a sign of supernatural power, within range. You create one of the following magical effects within range: Your voice booms up to three times as loud as normal for 1 minute. You cause flames to flicker, brighten, dim, or change color for 1 minute. You cause harmless tremors in the ground for 1 minute. You create an instantaneous sound that originates from a point of your choice within range. You instantaneously cause an unlocked door or window to fly open or slam shut. You alter the appearance of your eyes for 1 minute.",
    classes: ["cleric"],
    srdCompliant: true,
  },
  {
    name: "Druidcraft",
    level: 0,
    school: "transmutation",
    castingTime: "1 action",
    range: "30 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "Whispering to the spirits of nature, you create one of the following effects within range: You create a tiny, harmless sensory effect that predicts what the weather will be at your location for the next 24 hours. You instantly make a flower blossom, a seed pod open, or a leaf bud bloom. You create an instantaneous, harmless sensory effect, such as falling leaves, a puff of wind, the sound of a small animal, or the faint odor of skunk. You instantly light or snuff out a candle, a torch, or a small campfire.",
    classes: ["druid"],
    srdCompliant: true,
  },
  {
    name: "Eldritch Blast",
    level: 0,
    school: "evocation",
    castingTime: "1 action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 force damage. The spell creates more than one beam when you reach higher levels: two beams at 5th level, three beams at 11th level, and four beams at 17th level. You can direct the beams at the same target or at different ones. Make a separate attack roll for each beam.",
    classes: ["warlock"],
    damageType: "force",
    damageDice: "1d10",
    srdCompliant: true,
  },
  {
    name: "Minor Illusion",
    level: 0,
    school: "illusion",
    castingTime: "1 action",
    range: "30 feet",
    components: "S, M (a bit of fleece)",
    duration: "1 minute",
    description: "You create a sound or an image of an object within range that lasts for the duration. The illusion also ends if you dismiss it as an action or cast this spell again. If you create a sound, its volume can range from a whisper to a scream. If you create an image of an object it must be no larger than a 5-foot cube. The image can't create sound, light, smell, or any other sensory effect. Physical interaction with the image reveals it to be an illusion.",
    classes: ["bard", "sorcerer", "warlock", "wizard"],
    srdCompliant: true,
  },
  {
    name: "Poison Spray",
    level: 0,
    school: "conjuration",
    castingTime: "1 action",
    range: "10 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "You extend your hand toward a creature you can see within range and project a puff of noxious gas from your palm. The creature must succeed on a Constitution saving throw or take 1d12 poison damage. This spell's damage increases by 1d12 when you reach 5th level (2d12), 11th level (3d12), and 17th level (4d12).",
    classes: ["druid", "sorcerer", "warlock", "wizard"],
    damageType: "poison",
    damageDice: "1d12",
    savingThrow: "CON",
    srdCompliant: true,
  },
  {
    name: "Spare the Dying",
    level: 0,
    school: "necromancy",
    castingTime: "1 action",
    range: "Touch",
    components: "V, S",
    duration: "Instantaneous",
    description: "You touch a living creature that has 0 hit points. The creature becomes stable. This spell has no effect on undead or constructs.",
    classes: ["cleric"],
    srdCompliant: true,
  },
  {
    name: "Vicious Mockery",
    level: 0,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 feet",
    components: "V",
    duration: "Instantaneous",
    description: "You unleash a string of insults laced with subtle enchantments at a creature you can see within range. If the target can hear you (though it need not understand you), it must succeed on a Wisdom saving throw or take 1d4 psychic damage and have disadvantage on the next attack roll it makes before the end of its next turn. This spell's damage increases by 1d4 when you reach 5th level (2d4), 11th level (3d4), and 17th level (4d4).",
    classes: ["bard"],
    damageType: "psychic",
    damageDice: "1d4",
    savingThrow: "WIS",
    srdCompliant: true,
  },
  {
    name: "Chill Touch",
    level: 0,
    school: "necromancy",
    castingTime: "1 action",
    range: "120 feet",
    components: "V, S",
    duration: "1 round",
    description: "You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged spell attack against the creature. On a hit, the target takes 1d8 necrotic damage, and it can't regain hit points until the start of your next turn. If you hit an undead target, it also has disadvantage on attack rolls against you until the end of your next turn. This spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).",
    classes: ["sorcerer", "warlock", "wizard"],
    damageType: "necrotic",
    damageDice: "1d8",
    srdCompliant: true,
  },

  // LEVEL 1 SPELLS
  {
    name: "Magic Missile",
    level: 1,
    school: "evocation",
    castingTime: "1 action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4+1 force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.",
    higherLevels: "When you cast this spell using a spell slot of 2nd level or higher, the spell creates one more dart for each slot level above 1st.",
    classes: ["sorcerer", "wizard"],
    damageType: "force",
    damageDice: "1d4+1",
    srdCompliant: true,
  },
  {
    name: "Shield",
    level: 1,
    school: "abjuration",
    castingTime: "1 reaction",
    range: "Self",
    components: "V, S",
    duration: "1 round",
    description: "An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from magic missile.",
    classes: ["sorcerer", "wizard"],
    srdCompliant: true,
  },
  {
    name: "Burning Hands",
    level: 1,
    school: "evocation",
    castingTime: "1 action",
    range: "Self (15-foot cone)",
    components: "V, S",
    duration: "Instantaneous",
    description: "As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth from your outstretched fingertips. Each creature in a 15-foot cone must make a Dexterity saving throw. A creature takes 3d6 fire damage on a failed save, or half as much damage on a successful one. The fire ignites any flammable objects in the area that aren't being worn or carried.",
    higherLevels: "When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.",
    classes: ["sorcerer", "wizard"],
    damageType: "fire",
    damageDice: "3d6",
    savingThrow: "DEX",
    srdCompliant: true,
  },
  {
    name: "Cure Wounds",
    level: 1,
    school: "evocation",
    castingTime: "1 action",
    range: "Touch",
    components: "V, S",
    duration: "Instantaneous",
    description: "A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.",
    higherLevels: "When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d8 for each slot level above 1st.",
    classes: ["bard", "cleric", "druid", "paladin", "ranger"],
    healingDice: "1d8",
    srdCompliant: true,
  },
  {
    name: "Healing Word",
    level: 1,
    school: "evocation",
    castingTime: "1 bonus action",
    range: "60 feet",
    components: "V",
    duration: "Instantaneous",
    description: "A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier. This spell has no effect on undead or constructs.",
    higherLevels: "When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d4 for each slot level above 1st.",
    classes: ["bard", "cleric", "druid"],
    healingDice: "1d4",
    srdCompliant: true,
  },
  {
    name: "Bless",
    level: 1,
    school: "enchantment",
    castingTime: "1 action",
    range: "30 feet",
    components: "V, S, M (a sprinkling of holy water)",
    duration: "Concentration, up to 1 minute",
    description: "You bless up to three creatures of your choice within range. Whenever a target makes an attack roll or a saving throw before the spell ends, the target can roll a d4 and add the number rolled to the attack roll or saving throw.",
    higherLevels: "When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.",
    classes: ["cleric", "paladin"],
    concentration: true,
    srdCompliant: true,
  },
  {
    name: "Detect Magic",
    level: 1,
    school: "divination",
    castingTime: "1 action",
    range: "Self",
    components: "V, S",
    duration: "Concentration, up to 10 minutes",
    description: "For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object in the area that bears magic, and you learn its school of magic, if any. The spell can penetrate most barriers, but it is blocked by 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt.",
    classes: ["bard", "cleric", "druid", "paladin", "ranger", "sorcerer", "wizard"],
    ritual: true,
    concentration: true,
    srdCompliant: true,
  },
  {
    name: "Sleep",
    level: 1,
    school: "enchantment",
    castingTime: "1 action",
    range: "90 feet",
    components: "V, S, M (a pinch of fine sand, rose petals, or a cricket)",
    duration: "1 minute",
    description: "This spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect. Creatures within 20 feet of a point you choose within range are affected in ascending order of their current hit points (ignoring unconscious creatures). Starting with the creature that has the lowest current hit points, each creature affected by this spell falls unconscious until the spell ends, the sleeper takes damage, or someone uses an action to shake or slap the sleeper awake. Undead and creatures immune to being charmed aren't affected by this spell.",
    higherLevels: "When you cast this spell using a spell slot of 2nd level or higher, roll an additional 2d8 for each slot level above 1st.",
    classes: ["bard", "sorcerer", "wizard"],
    srdCompliant: true,
  },
  {
    name: "Thunderwave",
    level: 1,
    school: "evocation",
    castingTime: "1 action",
    range: "Self (15-foot cube)",
    components: "V, S",
    duration: "Instantaneous",
    description: "A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a Constitution saving throw. On a failed save, a creature takes 2d8 thunder damage and is pushed 10 feet away from you. On a successful save, the creature takes half as much damage and isn't pushed. In addition, unsecured objects that are completely within the area of effect are automatically pushed 10 feet away from you by the spell's effect, and the spell emits a thunderous boom audible out to 300 feet.",
    higherLevels: "When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d8 for each slot level above 1st.",
    classes: ["bard", "druid", "sorcerer", "wizard"],
    damageType: "thunder",
    damageDice: "2d8",
    savingThrow: "CON",
    srdCompliant: true,
  },
  {
    name: "Guiding Bolt",
    level: 1,
    school: "evocation",
    castingTime: "1 action",
    range: "120 feet",
    components: "V, S",
    duration: "1 round",
    description: "A flash of light streaks toward a creature of your choice within range. Make a ranged spell attack against the target. On a hit, the target takes 4d6 radiant damage, and the next attack roll made against this target before the end of your next turn has advantage, thanks to the mystical dim light glittering on the target until then.",
    higherLevels: "When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.",
    classes: ["cleric"],
    damageType: "radiant",
    damageDice: "4d6",
    srdCompliant: true,
  },
  {
    name: "Mage Armor",
    level: 1,
    school: "abjuration",
    castingTime: "1 action",
    range: "Touch",
    components: "V, S, M (a piece of cured leather)",
    duration: "8 hours",
    description: "You touch a willing creature who isn't wearing armor, and a protective magical force surrounds it until the spell ends. The target's base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss the spell as an action.",
    classes: ["sorcerer", "wizard"],
    srdCompliant: true,
  },
  {
    name: "Charm Person",
    level: 1,
    school: "enchantment",
    castingTime: "1 action",
    range: "30 feet",
    components: "V, S",
    duration: "1 hour",
    description: "You attempt to charm a humanoid you can see within range. It must make a Wisdom saving throw, and does so with advantage if you or your companions are fighting it. If it fails the saving throw, it is charmed by you until the spell ends or until you or your companions do anything harmful to it. The charmed creature regards you as a friendly acquaintance. When the spell ends, the creature knows it was charmed by you.",
    higherLevels: "When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.",
    classes: ["bard", "druid", "sorcerer", "warlock", "wizard"],
    savingThrow: "WIS",
    srdCompliant: true,
  },
  {
    name: "Inflict Wounds",
    level: 1,
    school: "necromancy",
    castingTime: "1 action",
    range: "Touch",
    components: "V, S",
    duration: "Instantaneous",
    description: "Make a melee spell attack against a creature you can reach. On a hit, the target takes 3d10 necrotic damage.",
    higherLevels: "When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d10 for each slot level above 1st.",
    classes: ["cleric"],
    damageType: "necrotic",
    damageDice: "3d10",
    srdCompliant: true,
  },
  {
    name: "Hex",
    level: 1,
    school: "enchantment",
    castingTime: "1 bonus action",
    range: "90 feet",
    components: "V, S, M (the petrified eye of a newt)",
    duration: "Concentration, up to 1 hour",
    description: "You place a curse on a creature that you can see within range. Until the spell ends, you deal an extra 1d6 necrotic damage to the target whenever you hit it with an attack. Also, choose one ability when you cast the spell. The target has disadvantage on ability checks made with the chosen ability. If the target drops to 0 hit points before this spell ends, you can use a bonus action on a subsequent turn of yours to curse a new creature.",
    higherLevels: "When you cast this spell using a spell slot of 3rd or 4th level, you can maintain your concentration on the spell for up to 8 hours. When you use a spell slot of 5th level or higher, you can maintain your concentration on the spell for up to 24 hours.",
    classes: ["warlock"],
    damageType: "necrotic",
    damageDice: "1d6",
    concentration: true,
    srdCompliant: true,
  },
  {
    name: "Entangle",
    level: 1,
    school: "conjuration",
    castingTime: "1 action",
    range: "90 feet",
    components: "V, S",
    duration: "Concentration, up to 1 minute",
    description: "Grasping weeds and vines sprout from the ground in a 20-foot square starting from a point within range. For the duration, these plants turn the ground in the area into difficult terrain. A creature in the area when you cast the spell must succeed on a Strength saving throw or be restrained by the entangling plants until the spell ends. A creature restrained by the plants can use its action to make a Strength check against your spell save DC. On a success, it frees itself.",
    classes: ["druid"],
    savingThrow: "STR",
    concentration: true,
    srdCompliant: true,
  },
  {
    name: "Faerie Fire",
    level: 1,
    school: "evocation",
    castingTime: "1 action",
    range: "60 feet",
    components: "V",
    duration: "Concentration, up to 1 minute",
    description: "Each object in a 20-foot cube within range is outlined in blue, green, or violet light (your choice). Any creature in the area when the spell is cast is also outlined in light if it fails a Dexterity saving throw. For the duration, objects and affected creatures shed dim light in a 10-foot radius. Any attack roll against an affected creature or object has advantage if the attacker can see it, and the affected creature or object can't benefit from being invisible.",
    classes: ["bard", "druid"],
    savingThrow: "DEX",
    concentration: true,
    srdCompliant: true,
  },
  {
    name: "Hunter's Mark",
    level: 1,
    school: "divination",
    castingTime: "1 bonus action",
    range: "90 feet",
    components: "V",
    duration: "Concentration, up to 1 hour",
    description: "You choose a creature you can see within range and mystically mark it as your quarry. Until the spell ends, you deal an extra 1d6 damage to the target whenever you hit it with a weapon attack, and you have advantage on any Wisdom (Perception) or Wisdom (Survival) check you make to find it. If the target drops to 0 hit points before this spell ends, you can use a bonus action on a subsequent turn of yours to mark a new creature.",
    higherLevels: "When you cast this spell using a spell slot of 3rd or 4th level, you can maintain your concentration on the spell for up to 8 hours. When you use a spell slot of 5th level or higher, you can maintain your concentration on the spell for up to 24 hours.",
    classes: ["ranger"],
    damageDice: "1d6",
    concentration: true,
    srdCompliant: true,
  },
  {
    name: "Divine Favor",
    level: 1,
    school: "evocation",
    castingTime: "1 bonus action",
    range: "Self",
    components: "V, S",
    duration: "Concentration, up to 1 minute",
    description: "Your prayer empowers you with divine radiance. Until the spell ends, your weapon attacks deal an extra 1d4 radiant damage on a hit.",
    classes: ["paladin"],
    damageType: "radiant",
    damageDice: "1d4",
    concentration: true,
    srdCompliant: true,
  },

  // LEVEL 2 SPELLS
  {
    name: "Scorching Ray",
    level: 2,
    school: "evocation",
    castingTime: "1 action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several. Make a ranged spell attack for each ray. On a hit, the target takes 2d6 fire damage.",
    higherLevels: "When you cast this spell using a spell slot of 3rd level or higher, you create one additional ray for each slot level above 2nd.",
    classes: ["sorcerer", "wizard"],
    damageType: "fire",
    damageDice: "2d6",
    srdCompliant: true,
  },
  {
    name: "Hold Person",
    level: 2,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 feet",
    components: "V, S, M (a small, straight piece of iron)",
    duration: "Concentration, up to 1 minute",
    description: "Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target.",
    higherLevels: "When you cast this spell using a spell slot of 3rd level or higher, you can target one additional humanoid for each slot level above 2nd.",
    classes: ["bard", "cleric", "druid", "sorcerer", "warlock", "wizard"],
    savingThrow: "WIS",
    concentration: true,
    srdCompliant: true,
  },
  {
    name: "Misty Step",
    level: 2,
    school: "conjuration",
    castingTime: "1 bonus action",
    range: "Self",
    components: "V",
    duration: "Instantaneous",
    description: "Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.",
    classes: ["sorcerer", "warlock", "wizard"],
    srdCompliant: true,
  },
  {
    name: "Spiritual Weapon",
    level: 2,
    school: "evocation",
    castingTime: "1 bonus action",
    range: "60 feet",
    components: "V, S",
    duration: "1 minute",
    description: "You create a floating, spectral weapon within range that lasts for the duration or until you cast this spell again. When you cast the spell, you can make a melee spell attack against a creature within 5 feet of the weapon. On a hit, the target takes force damage equal to 1d8 + your spellcasting ability modifier. As a bonus action on your turn, you can move the weapon up to 20 feet and repeat the attack against a creature within 5 feet of it.",
    higherLevels: "When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for every two slot levels above 2nd.",
    classes: ["cleric"],
    damageType: "force",
    damageDice: "1d8",
    srdCompliant: true,
  },
  {
    name: "Lesser Restoration",
    level: 2,
    school: "abjuration",
    castingTime: "1 action",
    range: "Touch",
    components: "V, S",
    duration: "Instantaneous",
    description: "You touch a creature and can end either one disease or one condition afflicting it. The condition can be blinded, deafened, paralyzed, or poisoned.",
    classes: ["bard", "cleric", "druid", "paladin", "ranger"],
    srdCompliant: true,
  },
  {
    name: "Invisibility",
    level: 2,
    school: "illusion",
    castingTime: "1 action",
    range: "Touch",
    components: "V, S, M (an eyelash encased in gum arabic)",
    duration: "Concentration, up to 1 hour",
    description: "A creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target's person. The spell ends for a target that attacks or casts a spell.",
    higherLevels: "When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.",
    classes: ["bard", "sorcerer", "warlock", "wizard"],
    concentration: true,
    srdCompliant: true,
  },
  {
    name: "Shatter",
    level: 2,
    school: "evocation",
    castingTime: "1 action",
    range: "60 feet",
    components: "V, S, M (a chip of mica)",
    duration: "Instantaneous",
    description: "A sudden loud ringing noise, painfully intense, erupts from a point of your choice within range. Each creature in a 10-foot-radius sphere centered on that point must make a Constitution saving throw. A creature takes 3d8 thunder damage on a failed save, or half as much damage on a successful one. A creature made of inorganic material such as stone, crystal, or metal has disadvantage on this saving throw. A nonmagical object that isn't being worn or carried also takes the damage if it's in the spell's area.",
    higherLevels: "When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for each slot level above 2nd.",
    classes: ["bard", "sorcerer", "warlock", "wizard"],
    damageType: "thunder",
    damageDice: "3d8",
    savingThrow: "CON",
    srdCompliant: true,
  },
  {
    name: "Prayer of Healing",
    level: 2,
    school: "evocation",
    castingTime: "10 minutes",
    range: "30 feet",
    components: "V",
    duration: "Instantaneous",
    description: "Up to six creatures of your choice that you can see within range each regain hit points equal to 2d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.",
    higherLevels: "When you cast this spell using a spell slot of 3rd level or higher, the healing increases by 1d8 for each slot level above 2nd.",
    classes: ["cleric"],
    healingDice: "2d8",
    srdCompliant: true,
  },
  {
    name: "Moonbeam",
    level: 2,
    school: "evocation",
    castingTime: "1 action",
    range: "120 feet",
    components: "V, S, M (several seeds of any moonseed plant and a piece of opalescent feldspar)",
    duration: "Concentration, up to 1 minute",
    description: "A silvery beam of pale light shines down in a 5-foot-radius, 40-foot-high cylinder centered on a point within range. Until the spell ends, dim light fills the cylinder. When a creature enters the spell's area for the first time on a turn or starts its turn there, it is engulfed in ghostly flames that cause searing pain, and it must make a Constitution saving throw. It takes 2d10 radiant damage on a failed save, or half as much damage on a successful one. A shapechanger makes its saving throw with disadvantage.",
    higherLevels: "When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d10 for each slot level above 2nd.",
    classes: ["druid"],
    damageType: "radiant",
    damageDice: "2d10",
    savingThrow: "CON",
    concentration: true,
    srdCompliant: true,
  },
  {
    name: "Smite",
    level: 2,
    school: "evocation",
    castingTime: "1 bonus action",
    range: "Self",
    components: "V",
    duration: "Concentration, up to 1 minute",
    description: "The next time you hit a creature with a melee weapon attack during this spell's duration, your weapon flares with radiance and the attack deals an extra 2d6 radiant damage to the target. If the target is a fiend or an undead, the damage is 3d6 instead.",
    higherLevels: "When you cast this spell using a spell slot of 3rd level or higher, the extra damage increases by 1d6 for each slot level above 2nd.",
    classes: ["paladin"],
    damageType: "radiant",
    damageDice: "2d6",
    concentration: true,
    srdCompliant: true,
  },

  // LEVEL 3 SPELLS
  {
    name: "Fireball",
    level: 3,
    school: "evocation",
    castingTime: "1 action",
    range: "150 feet",
    components: "V, S, M (a tiny ball of bat guano and sulfur)",
    duration: "Instantaneous",
    description: "A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one. The fire spreads around corners. It ignites flammable objects in the area that aren't being worn or carried.",
    higherLevels: "When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.",
    classes: ["sorcerer", "wizard"],
    damageType: "fire",
    damageDice: "8d6",
    savingThrow: "DEX",
    srdCompliant: true,
  },
  {
    name: "Lightning Bolt",
    level: 3,
    school: "evocation",
    castingTime: "1 action",
    range: "Self (100-foot line)",
    components: "V, S, M (a bit of fur and a rod of amber, crystal, or glass)",
    duration: "Instantaneous",
    description: "A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out from you in a direction you choose. Each creature in the line must make a Dexterity saving throw. A creature takes 8d6 lightning damage on a failed save, or half as much damage on a successful one. The lightning ignites flammable objects in the area that aren't being worn or carried.",
    higherLevels: "When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.",
    classes: ["sorcerer", "wizard"],
    damageType: "lightning",
    damageDice: "8d6",
    savingThrow: "DEX",
    srdCompliant: true,
  },
  {
    name: "Counterspell",
    level: 3,
    school: "abjuration",
    castingTime: "1 reaction",
    range: "60 feet",
    components: "S",
    duration: "Instantaneous",
    description: "You attempt to interrupt a creature in the process of casting a spell. If the creature is casting a spell of 3rd level or lower, its spell fails and has no effect. If it is casting a spell of 4th level or higher, make an ability check using your spellcasting ability. The DC equals 10 + the spell's level. On a success, the creature's spell fails and has no effect.",
    higherLevels: "When you cast this spell using a spell slot of 4th level or higher, the interrupted spell has no effect if its level is less than or equal to the level of the spell slot you used.",
    classes: ["sorcerer", "warlock", "wizard"],
    srdCompliant: true,
  },
  {
    name: "Dispel Magic",
    level: 3,
    school: "abjuration",
    castingTime: "1 action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends. For each spell of 4th level or higher on the target, make an ability check using your spellcasting ability. The DC equals 10 + the spell's level. On a successful check, the spell ends.",
    higherLevels: "When you cast this spell using a spell slot of 4th level or higher, you automatically end the effects of a spell on the target if the spell's level is equal to or less than the level of the spell slot you used.",
    classes: ["bard", "cleric", "druid", "paladin", "sorcerer", "warlock", "wizard"],
    srdCompliant: true,
  },
  {
    name: "Revivify",
    level: 3,
    school: "necromancy",
    castingTime: "1 action",
    range: "Touch",
    components: "V, S, M (diamonds worth 300 gp, which the spell consumes)",
    duration: "Instantaneous",
    description: "You touch a creature that has died within the last minute. That creature returns to life with 1 hit point. This spell can't return to life a creature that has died of old age, nor can it restore any missing body parts.",
    classes: ["cleric", "paladin"],
    healingDice: "1",
    srdCompliant: true,
  },
  {
    name: "Spirit Guardians",
    level: 3,
    school: "conjuration",
    castingTime: "1 action",
    range: "Self (15-foot radius)",
    components: "V, S, M (a holy symbol)",
    duration: "Concentration, up to 10 minutes",
    description: "You call forth spirits to protect you. They flit around you to a distance of 15 feet for the duration. If you are good or neutral, their spectral form appears angelic or fey (your choice). If you are evil, they appear fiendish. When you cast this spell, you can designate any number of creatures you can see to be unaffected by it. An affected creature's speed is halved in the area, and when the creature enters the area for the first time on a turn or starts its turn there, it must make a Wisdom saving throw. On a failed save, the creature takes 3d8 radiant damage (if you are good or neutral) or 3d8 necrotic damage (if you are evil). On a successful save, the creature takes half as much damage.",
    higherLevels: "When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d8 for each slot level above 3rd.",
    classes: ["cleric"],
    damageType: "radiant",
    damageDice: "3d8",
    savingThrow: "WIS",
    concentration: true,
    srdCompliant: true,
  },
  {
    name: "Haste",
    level: 3,
    school: "transmutation",
    castingTime: "1 action",
    range: "30 feet",
    components: "V, S, M (a shaving of licorice root)",
    duration: "Concentration, up to 1 minute",
    description: "Choose a willing creature that you can see within range. Until the spell ends, the target's speed is doubled, it gains a +2 bonus to AC, it has advantage on Dexterity saving throws, and it gains an additional action on each of its turns. That action can be used only to take the Attack (one weapon attack only), Dash, Disengage, Hide, or Use an Object action. When the spell ends, the target can't move or take actions until after its next turn, as a wave of lethargy sweeps over it.",
    classes: ["sorcerer", "wizard"],
    concentration: true,
    srdCompliant: true,
  },
  {
    name: "Fly",
    level: 3,
    school: "transmutation",
    castingTime: "1 action",
    range: "Touch",
    components: "V, S, M (a wing feather from any bird)",
    duration: "Concentration, up to 10 minutes",
    description: "You touch a willing creature. The target gains a flying speed of 60 feet for the duration. When the spell ends, the target falls if it is still aloft, unless it can stop the fall.",
    higherLevels: "When you cast this spell using a spell slot of 4th level or higher, you can target one additional creature for each slot level above 3rd.",
    classes: ["sorcerer", "warlock", "wizard"],
    concentration: true,
    srdCompliant: true,
  },
  {
    name: "Call Lightning",
    level: 3,
    school: "conjuration",
    castingTime: "1 action",
    range: "120 feet",
    components: "V, S",
    duration: "Concentration, up to 10 minutes",
    description: "A storm cloud appears in the shape of a cylinder that is 10 feet tall with a 60-foot radius, centered on a point you can see within range directly above you. The spell fails if you can't see a point in the air where the storm cloud could appear. When you cast the spell, choose a point you can see under the cloud. A bolt of lightning flashes down from the cloud to that point. Each creature within 5 feet of that point must make a Dexterity saving throw. A creature takes 3d10 lightning damage on a failed save, or half as much damage on a successful one. On each of your turns until the spell ends, you can use your action to call down lightning in this way again, targeting the same point or a different one.",
    higherLevels: "When you cast this spell using a spell slot of 4th or higher level, the damage increases by 1d10 for each slot level above 3rd.",
    classes: ["druid"],
    damageType: "lightning",
    damageDice: "3d10",
    savingThrow: "DEX",
    concentration: true,
    srdCompliant: true,
  },

  // LEVEL 4 SPELLS
  {
    name: "Ice Storm",
    level: 4,
    school: "evocation",
    castingTime: "1 action",
    range: "300 feet",
    components: "V, S, M (a pinch of dust and a few drops of water)",
    duration: "Instantaneous",
    description: "A hail of rock-hard ice pounds to the ground in a 20-foot-radius, 40-foot-high cylinder centered on a point within range. Each creature in the cylinder must make a Dexterity saving throw. A creature takes 2d8 bludgeoning damage and 4d6 cold damage on a failed save, or half as much damage on a successful one. Hailstones turn the storm's area of effect into difficult terrain until the end of your next turn.",
    higherLevels: "When you cast this spell using a spell slot of 5th level or higher, the bludgeoning damage increases by 1d8 for each slot level above 4th.",
    classes: ["druid", "sorcerer", "wizard"],
    damageType: "cold",
    damageDice: "4d6",
    savingThrow: "DEX",
    srdCompliant: true,
  },
  {
    name: "Dimension Door",
    level: 4,
    school: "conjuration",
    castingTime: "1 action",
    range: "500 feet",
    components: "V",
    duration: "Instantaneous",
    description: "You teleport yourself from your current location to any other spot within range. You arrive at exactly the spot desired. It can be a place you can see, one you can visualize, or one you can describe by stating distance and direction. You can bring along objects as long as their weight doesn't exceed what you can carry. You can also bring one willing creature of your size or smaller who is carrying gear up to its carrying capacity. If you would arrive in a place already occupied by an object or a creature, you and any creature traveling with you each take 4d6 force damage, and the spell fails to teleport you.",
    classes: ["bard", "sorcerer", "warlock", "wizard"],
    srdCompliant: true,
  },
  {
    name: "Greater Invisibility",
    level: 4,
    school: "illusion",
    castingTime: "1 action",
    range: "Touch",
    components: "V, S",
    duration: "Concentration, up to 1 minute",
    description: "You or a creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target's person.",
    classes: ["bard", "sorcerer", "wizard"],
    concentration: true,
    srdCompliant: true,
  },
  {
    name: "Banishment",
    level: 4,
    school: "abjuration",
    castingTime: "1 action",
    range: "60 feet",
    components: "V, S, M (an item distasteful to the target)",
    duration: "Concentration, up to 1 minute",
    description: "You attempt to send one creature that you can see within range to another plane of existence. The target must succeed on a Charisma saving throw or be banished. If the target is native to the plane of existence you're on, you banish the target to a harmless demiplane. While there, the target is incapacitated. The target remains there until the spell ends, at which point the target reappears in the space it left or in the nearest unoccupied space if that space is occupied. If the target is native to a different plane of existence than the one you're on, the target is banished with a faint popping noise, returning to its home plane. If the spell ends before 1 minute has passed, the target reappears in the space it left or in the nearest unoccupied space if that space is occupied. Otherwise, the target doesn't return.",
    higherLevels: "When you cast this spell using a spell slot of 5th level or higher, you can target one additional creature for each slot level above 4th.",
    classes: ["cleric", "paladin", "sorcerer", "warlock", "wizard"],
    savingThrow: "CHA",
    concentration: true,
    srdCompliant: true,
  },
  {
    name: "Polymorph",
    level: 4,
    school: "transmutation",
    castingTime: "1 action",
    range: "60 feet",
    components: "V, S, M (a caterpillar cocoon)",
    duration: "Concentration, up to 1 hour",
    description: "This spell transforms a creature that you can see within range into a new form. An unwilling creature must make a Wisdom saving throw to avoid the effect. The spell has no effect on a shapechanger or a creature with 0 hit points. The transformation lasts for the duration, or until the target drops to 0 hit points or dies. The new form can be any beast whose challenge rating is equal to or less than the target's (or the target's level, if it doesn't have a challenge rating). The target's game statistics, including mental ability scores, are replaced by the statistics of the chosen beast. It retains its alignment and personality.",
    classes: ["bard", "druid", "sorcerer", "wizard"],
    savingThrow: "WIS",
    concentration: true,
    srdCompliant: true,
  },

  // LEVEL 5 SPELLS
  {
    name: "Cone of Cold",
    level: 5,
    school: "evocation",
    castingTime: "1 action",
    range: "Self (60-foot cone)",
    components: "V, S, M (a small crystal or glass cone)",
    duration: "Instantaneous",
    description: "A blast of cold air erupts from your hands. Each creature in a 60-foot cone must make a Constitution saving throw. A creature takes 8d8 cold damage on a failed save, or half as much damage on a successful one. A creature killed by this spell becomes a frozen statue until it thaws.",
    higherLevels: "When you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d8 for each slot level above 5th.",
    classes: ["sorcerer", "wizard"],
    damageType: "cold",
    damageDice: "8d8",
    savingThrow: "CON",
    srdCompliant: true,
  },
  {
    name: "Mass Cure Wounds",
    level: 5,
    school: "evocation",
    castingTime: "1 action",
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "A wave of healing energy washes out from a point of your choice within range. Choose up to six creatures in a 30-foot-radius sphere centered on that point. Each target regains hit points equal to 3d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.",
    higherLevels: "When you cast this spell using a spell slot of 6th level or higher, the healing increases by 1d8 for each slot level above 5th.",
    classes: ["bard", "cleric", "druid"],
    healingDice: "3d8",
    srdCompliant: true,
  },
  {
    name: "Hold Monster",
    level: 5,
    school: "enchantment",
    castingTime: "1 action",
    range: "90 feet",
    components: "V, S, M (a small, straight piece of iron)",
    duration: "Concentration, up to 1 minute",
    description: "Choose a creature that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. This spell has no effect on undead. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target.",
    higherLevels: "When you cast this spell using a spell slot of 6th level or higher, you can target one additional creature for each slot level above 5th.",
    classes: ["bard", "sorcerer", "warlock", "wizard"],
    savingThrow: "WIS",
    concentration: true,
    srdCompliant: true,
  },
  {
    name: "Raise Dead",
    level: 5,
    school: "necromancy",
    castingTime: "1 hour",
    range: "Touch",
    components: "V, S, M (a diamond worth at least 500 gp, which the spell consumes)",
    duration: "Instantaneous",
    description: "You return a dead creature you touch to life, provided that it has been dead no longer than 10 days. If the creature's soul is both willing and at liberty to rejoin the body, the creature returns to life with 1 hit point. This spell also neutralizes any poisons and cures nonmagical diseases that affected the creature at the time it died. This spell doesn't, however, remove magical diseases, curses, or similar effects; if these aren't first removed prior to casting the spell, they take effect when the creature returns to life. This spell can't return to life a creature that has died of old age, nor can it restore any missing body parts. Coming back from the dead is an ordeal. The target takes a −4 penalty to all attack rolls, saving throws, and ability checks. Every time the target finishes a long rest, the penalty is reduced by 1 until it disappears.",
    classes: ["bard", "cleric", "paladin"],
    healingDice: "1",
    srdCompliant: true,
  },
  {
    name: "Wall of Force",
    level: 5,
    school: "evocation",
    castingTime: "1 action",
    range: "120 feet",
    components: "V, S, M (a pinch of powder made by crushing a clear gemstone)",
    duration: "Concentration, up to 10 minutes",
    description: "An invisible wall of force springs into existence at a point you choose within range. The wall appears in any orientation you choose, as a horizontal or vertical barrier or at an angle. It can be free floating or resting on a solid surface. You can form it into a hemispherical dome or a sphere with a radius of up to 10 feet, or you can shape a flat surface made up of ten 10-foot-by-10-foot panels. Each panel must be contiguous with another panel. The wall is 1/4 inch thick. It lasts for the duration. If the wall cuts through a creature's space when it appears, the creature is pushed to one side of the wall (your choice which side). Nothing can physically pass through the wall. It is immune to all damage and can't be dispelled by dispel magic. A disintegrate spell destroys the wall instantly, however. The wall also extends into the Ethereal Plane, blocking ethereal travel through the wall.",
    classes: ["wizard"],
    concentration: true,
    srdCompliant: true,
  },

  // LEVEL 6 SPELLS
  {
    name: "Chain Lightning",
    level: 6,
    school: "evocation",
    castingTime: "1 action",
    range: "150 feet",
    components: "V, S, M (a bit of fur; a piece of amber, glass, or a crystal rod; and three silver pins)",
    duration: "Instantaneous",
    description: "You create a bolt of lightning that arcs toward a target of your choice that you can see within range. Three bolts then leap from that target to as many as three other targets, each of which must be within 30 feet of the first target. A target can be a creature or an object and can be targeted by only one of the bolts. A target must make a Dexterity saving throw. The target takes 10d8 lightning damage on a failed save, or half as much damage on a successful one.",
    higherLevels: "When you cast this spell using a spell slot of 7th level or higher, one additional bolt leaps from the first target to another target for each slot level above 6th.",
    classes: ["sorcerer", "wizard"],
    damageType: "lightning",
    damageDice: "10d8",
    savingThrow: "DEX",
    srdCompliant: true,
  },
  {
    name: "Disintegrate",
    level: 6,
    school: "transmutation",
    castingTime: "1 action",
    range: "60 feet",
    components: "V, S, M (a lodestone and a pinch of dust)",
    duration: "Instantaneous",
    description: "A thin green ray springs from your pointing finger to a target that you can see within range. The target can be a creature, an object, or a creation of magical force, such as the wall created by wall of force. A creature targeted by this spell must make a Dexterity saving throw. On a failed save, the target takes 10d6 + 40 force damage. The target is disintegrated if this damage leaves it with 0 hit points. A disintegrated creature and everything it is wearing and carrying, except magic items, are reduced to a pile of fine gray dust.",
    higherLevels: "When you cast this spell using a spell slot of 7th level or higher, the damage increases by 3d6 for each slot level above 6th.",
    classes: ["sorcerer", "wizard"],
    damageType: "force",
    damageDice: "10d6+40",
    savingThrow: "DEX",
    srdCompliant: true,
  },
  {
    name: "Heal",
    level: 6,
    school: "evocation",
    castingTime: "1 action",
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "Choose a creature that you can see within range. A surge of positive energy washes through the creature, causing it to regain 70 hit points. This spell also ends blindness, deafness, and any diseases affecting the target. This spell has no effect on constructs or undead.",
    higherLevels: "When you cast this spell using a spell slot of 7th level or higher, the amount of healing increases by 10 for each slot level above 6th.",
    classes: ["cleric", "druid"],
    healingDice: "70",
    srdCompliant: true,
  },
  {
    name: "True Seeing",
    level: 6,
    school: "divination",
    castingTime: "1 action",
    range: "Touch",
    components: "V, S, M (an ointment for the eyes that costs 25 gp; is made from mushroom powder, saffron, and fat; and is consumed by the spell)",
    duration: "1 hour",
    description: "This spell gives the willing creature you touch the ability to see things as they actually are. For the duration, the creature has truesight, notices secret doors hidden by magic, and can see into the Ethereal Plane, all out to a range of 120 feet.",
    classes: ["bard", "cleric", "sorcerer", "warlock", "wizard"],
    srdCompliant: true,
  },

  // LEVEL 7 SPELLS
  {
    name: "Finger of Death",
    level: 7,
    school: "necromancy",
    castingTime: "1 action",
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "You send negative energy coursing through a creature that you can see within range, causing it searing pain. The target must make a Constitution saving throw. It takes 7d8 + 30 necrotic damage on a failed save, or half as much damage on a successful one. A humanoid killed by this spell rises at the start of your next turn as a zombie that is permanently under your command, following your verbal orders to the best of its ability.",
    classes: ["sorcerer", "warlock", "wizard"],
    damageType: "necrotic",
    damageDice: "7d8+30",
    savingThrow: "CON",
    srdCompliant: true,
  },
  {
    name: "Resurrection",
    level: 7,
    school: "necromancy",
    castingTime: "1 hour",
    range: "Touch",
    components: "V, S, M (a diamond worth at least 1,000 gp, which the spell consumes)",
    duration: "Instantaneous",
    description: "You touch a dead creature that has been dead for no more than a century, that didn't die of old age, and that isn't undead. If its soul is free and willing, the target returns to life with all its hit points. This spell neutralizes any poisons and cures normal diseases afflicting the creature when it died. It doesn't, however, remove magical diseases, curses, and the like; if such effects aren't removed prior to casting the spell, they afflict the target on its return to life. This spell closes all mortal wounds and restores any missing body parts. Coming back from the dead is an ordeal. The target takes a −4 penalty to all attack rolls, saving throws, and ability checks. Every time the target finishes a long rest, the penalty is reduced by 1 until it disappears.",
    classes: ["bard", "cleric"],
    srdCompliant: true,
  },
  {
    name: "Teleport",
    level: 7,
    school: "conjuration",
    castingTime: "1 action",
    range: "10 feet",
    components: "V",
    duration: "Instantaneous",
    description: "This spell instantly transports you and up to eight willing creatures of your choice that you can see within range, or a single object that you can see within range, to a destination you select. If you target an object, it must be able to fit entirely inside a 10-foot cube, and it can't be held or carried by an unwilling creature. The destination you choose must be known to you, and it must be on the same plane of existence as you. Your familiarity with the destination determines whether you arrive there successfully.",
    classes: ["bard", "sorcerer", "wizard"],
    srdCompliant: true,
  },

  // LEVEL 8 SPELLS
  {
    name: "Power Word Stun",
    level: 8,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 feet",
    components: "V",
    duration: "Instantaneous",
    description: "You speak a word of power that can overwhelm the mind of one creature you can see within range, leaving it dumbfounded. If the target has 150 hit points or fewer, it is stunned. Otherwise, the spell has no effect. The stunned target must make a Constitution saving throw at the end of each of its turns. On a successful save, this stunning effect ends.",
    classes: ["bard", "sorcerer", "warlock", "wizard"],
    savingThrow: "CON",
    srdCompliant: true,
  },
  {
    name: "Sunburst",
    level: 8,
    school: "evocation",
    castingTime: "1 action",
    range: "150 feet",
    components: "V, S, M (fire and a piece of sunstone)",
    duration: "Instantaneous",
    description: "Brilliant sunlight flashes in a 60-foot radius centered on a point you choose within range. Each creature in that light must make a Constitution saving throw. On a failed save, a creature takes 12d6 radiant damage and is blinded for 1 minute. On a successful save, it takes half as much damage and isn't blinded by this spell. Undead and oozes have disadvantage on this saving throw. A creature blinded by this spell makes another Constitution saving throw at the end of each of its turns. On a successful save, it is no longer blinded.",
    classes: ["druid", "sorcerer", "wizard"],
    damageType: "radiant",
    damageDice: "12d6",
    savingThrow: "CON",
    srdCompliant: true,
  },
  {
    name: "Dominate Monster",
    level: 8,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 feet",
    components: "V, S",
    duration: "Concentration, up to 1 hour",
    description: "You attempt to beguile a creature that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration. If you or creatures that are friendly to you are fighting it, it has advantage on the saving throw. While the creature is charmed, you have a telepathic link with it as long as the two of you are on the same plane of existence. You can use this telepathic link to issue commands to the creature while you are conscious (no action required), which it does its best to obey. Each time the target takes damage, it makes a new Wisdom saving throw against the spell. If the saving throw succeeds, the spell ends.",
    classes: ["bard", "sorcerer", "warlock", "wizard"],
    savingThrow: "WIS",
    concentration: true,
    srdCompliant: true,
  },

  // LEVEL 9 SPELLS
  {
    name: "Wish",
    level: 9,
    school: "conjuration",
    castingTime: "1 action",
    range: "Self",
    components: "V",
    duration: "Instantaneous",
    description: "Wish is the mightiest spell a mortal creature can cast. By simply speaking aloud, you can alter the very foundations of reality in accord with your desires. The basic use of this spell is to duplicate any other spell of 8th level or lower. You don't need to meet any requirements in that spell, including costly components. The spell simply takes effect. Alternatively, you can create one of the following effects of your choice: You create one object of up to 25,000 gp in value that isn't a magic item. You allow up to twenty creatures that you can see to regain all hit points, and you end all effects on them described in the greater restoration spell. You grant up to ten creatures that you can see resistance to a damage type you choose. You grant up to ten creatures you can see immunity to a single spell or other magical effect for 8 hours. You undo a single recent event by forcing a reroll of any roll made within the last round.",
    classes: ["sorcerer", "wizard"],
    srdCompliant: true,
  },
  {
    name: "Power Word Kill",
    level: 9,
    school: "enchantment",
    castingTime: "1 action",
    range: "60 feet",
    components: "V",
    duration: "Instantaneous",
    description: "You utter a word of power that can compel one creature you can see within range to die instantly. If the creature you choose has 100 hit points or fewer, it dies. Otherwise, the spell has no effect.",
    classes: ["bard", "sorcerer", "warlock", "wizard"],
    srdCompliant: true,
  },
  {
    name: "Meteor Swarm",
    level: 9,
    school: "evocation",
    castingTime: "1 action",
    range: "1 mile",
    components: "V, S",
    duration: "Instantaneous",
    description: "Blazing orbs of fire plummet to the ground at four different points you can see within range. Each creature in a 40-foot-radius sphere centered on each point you choose must make a Dexterity saving throw. The sphere spreads around corners. A creature takes 20d6 fire damage and 20d6 bludgeoning damage on a failed save, or half as much damage on a successful one. A creature in the area of more than one fiery burst is affected only once. The spell damages objects in the area and ignites flammable objects that aren't being worn or carried.",
    classes: ["sorcerer", "wizard"],
    damageType: "fire",
    damageDice: "40d6",
    savingThrow: "DEX",
    srdCompliant: true,
  },
  {
    name: "True Resurrection",
    level: 9,
    school: "necromancy",
    castingTime: "1 hour",
    range: "Touch",
    components: "V, S, M (a sprinkle of holy water and diamonds worth at least 25,000 gp, which the spell consumes)",
    duration: "Instantaneous",
    description: "You touch a creature that has been dead for no longer than 200 years and that died for any reason except old age. If the creature's soul is free and willing, the creature is restored to life with all its hit points. This spell closes all wounds, neutralizes any poison, cures all diseases, and lifts any curses affecting the creature when it died. The spell replaces damaged or missing organs and limbs. If the creature was undead, it is restored to its non-undead form. The spell can even provide a new body if the original no longer exists, in which case you must speak the creature's name. The creature then appears in an unoccupied space you choose within 10 feet of you.",
    classes: ["cleric", "druid"],
    srdCompliant: true,
  },
];

export function getSpellsByClass(className: string): typeof SRD_SPELLS {
  const normalizedClass = className.toLowerCase();
  return SRD_SPELLS.filter(spell => 
    spell.classes.includes(normalizedClass)
  );
}

export function getSpellsByLevel(level: number): typeof SRD_SPELLS {
  return SRD_SPELLS.filter(spell => spell.level === level);
}

export function getSpellsBySchool(school: string): typeof SRD_SPELLS {
  return SRD_SPELLS.filter(spell => 
    spell.school.toLowerCase() === school.toLowerCase()
  );
}

export function getSpellsAvailableForCharacter(
  characterClass: string, 
  characterLevel: number
): typeof SRD_SPELLS {
  const maxSpellLevel = getMaxSpellLevel(characterClass, characterLevel);
  return getSpellsByClass(characterClass).filter(spell => 
    spell.level <= maxSpellLevel
  );
}

export function getMaxSpellLevel(characterClass: string, characterLevel: number): number {
  const fullCasters = ["wizard", "sorcerer", "cleric", "druid", "bard"];
  const halfCasters = ["paladin", "ranger"];
  const thirdCasters = ["eldritch knight", "arcane trickster"];
  
  const classLower = characterClass.toLowerCase();
  
  if (fullCasters.includes(classLower)) {
    if (characterLevel >= 17) return 9;
    if (characterLevel >= 15) return 8;
    if (characterLevel >= 13) return 7;
    if (characterLevel >= 11) return 6;
    if (characterLevel >= 9) return 5;
    if (characterLevel >= 7) return 4;
    if (characterLevel >= 5) return 3;
    if (characterLevel >= 3) return 2;
    return 1;
  }
  
  if (halfCasters.includes(classLower)) {
    if (characterLevel < 2) return 0;
    if (characterLevel >= 17) return 5;
    if (characterLevel >= 13) return 4;
    if (characterLevel >= 9) return 3;
    if (characterLevel >= 5) return 2;
    return 1;
  }
  
  if (classLower === "warlock") {
    if (characterLevel >= 9) return 5;
    if (characterLevel >= 7) return 4;
    if (characterLevel >= 5) return 3;
    if (characterLevel >= 3) return 2;
    return 1;
  }
  
  return 0;
}

export function getSpellSlotsByLevel(characterClass: string, characterLevel: number): number[] {
  const fullCasters = ["wizard", "sorcerer", "cleric", "druid", "bard"];
  const halfCasters = ["paladin", "ranger"];
  
  const classLower = characterClass.toLowerCase();
  
  const fullCasterSlots: { [key: number]: number[] } = {
    1: [2, 0, 0, 0, 0, 0, 0, 0, 0],
    2: [3, 0, 0, 0, 0, 0, 0, 0, 0],
    3: [4, 2, 0, 0, 0, 0, 0, 0, 0],
    4: [4, 3, 0, 0, 0, 0, 0, 0, 0],
    5: [4, 3, 2, 0, 0, 0, 0, 0, 0],
    6: [4, 3, 3, 0, 0, 0, 0, 0, 0],
    7: [4, 3, 3, 1, 0, 0, 0, 0, 0],
    8: [4, 3, 3, 2, 0, 0, 0, 0, 0],
    9: [4, 3, 3, 3, 1, 0, 0, 0, 0],
    10: [4, 3, 3, 3, 2, 0, 0, 0, 0],
    11: [4, 3, 3, 3, 2, 1, 0, 0, 0],
    12: [4, 3, 3, 3, 2, 1, 0, 0, 0],
    13: [4, 3, 3, 3, 2, 1, 1, 0, 0],
    14: [4, 3, 3, 3, 2, 1, 1, 0, 0],
    15: [4, 3, 3, 3, 2, 1, 1, 1, 0],
    16: [4, 3, 3, 3, 2, 1, 1, 1, 0],
    17: [4, 3, 3, 3, 2, 1, 1, 1, 1],
    18: [4, 3, 3, 3, 3, 1, 1, 1, 1],
    19: [4, 3, 3, 3, 3, 2, 1, 1, 1],
    20: [4, 3, 3, 3, 3, 2, 2, 1, 1],
  };
  
  const halfCasterSlots: { [key: number]: number[] } = {
    1: [0, 0, 0, 0, 0, 0, 0, 0, 0],
    2: [2, 0, 0, 0, 0, 0, 0, 0, 0],
    3: [3, 0, 0, 0, 0, 0, 0, 0, 0],
    4: [3, 0, 0, 0, 0, 0, 0, 0, 0],
    5: [4, 2, 0, 0, 0, 0, 0, 0, 0],
    6: [4, 2, 0, 0, 0, 0, 0, 0, 0],
    7: [4, 3, 0, 0, 0, 0, 0, 0, 0],
    8: [4, 3, 0, 0, 0, 0, 0, 0, 0],
    9: [4, 3, 2, 0, 0, 0, 0, 0, 0],
    10: [4, 3, 2, 0, 0, 0, 0, 0, 0],
    11: [4, 3, 3, 0, 0, 0, 0, 0, 0],
    12: [4, 3, 3, 0, 0, 0, 0, 0, 0],
    13: [4, 3, 3, 1, 0, 0, 0, 0, 0],
    14: [4, 3, 3, 1, 0, 0, 0, 0, 0],
    15: [4, 3, 3, 2, 0, 0, 0, 0, 0],
    16: [4, 3, 3, 2, 0, 0, 0, 0, 0],
    17: [4, 3, 3, 3, 1, 0, 0, 0, 0],
    18: [4, 3, 3, 3, 1, 0, 0, 0, 0],
    19: [4, 3, 3, 3, 2, 0, 0, 0, 0],
    20: [4, 3, 3, 3, 2, 0, 0, 0, 0],
  };
  
  const warlockSlots: { [key: number]: number[] } = {
    1: [1, 0, 0, 0, 0, 0, 0, 0, 0],
    2: [2, 0, 0, 0, 0, 0, 0, 0, 0],
    3: [0, 2, 0, 0, 0, 0, 0, 0, 0],
    4: [0, 2, 0, 0, 0, 0, 0, 0, 0],
    5: [0, 0, 2, 0, 0, 0, 0, 0, 0],
    6: [0, 0, 2, 0, 0, 0, 0, 0, 0],
    7: [0, 0, 0, 2, 0, 0, 0, 0, 0],
    8: [0, 0, 0, 2, 0, 0, 0, 0, 0],
    9: [0, 0, 0, 0, 2, 0, 0, 0, 0],
    10: [0, 0, 0, 0, 2, 0, 0, 0, 0],
    11: [0, 0, 0, 0, 3, 0, 0, 0, 0],
    12: [0, 0, 0, 0, 3, 0, 0, 0, 0],
    13: [0, 0, 0, 0, 3, 0, 0, 0, 0],
    14: [0, 0, 0, 0, 3, 0, 0, 0, 0],
    15: [0, 0, 0, 0, 3, 0, 0, 0, 0],
    16: [0, 0, 0, 0, 3, 0, 0, 0, 0],
    17: [0, 0, 0, 0, 4, 0, 0, 0, 0],
    18: [0, 0, 0, 0, 4, 0, 0, 0, 0],
    19: [0, 0, 0, 0, 4, 0, 0, 0, 0],
    20: [0, 0, 0, 0, 4, 0, 0, 0, 0],
  };
  
  const level = Math.min(Math.max(characterLevel, 1), 20);
  
  if (fullCasters.includes(classLower)) {
    return fullCasterSlots[level] || [0, 0, 0, 0, 0, 0, 0, 0, 0];
  }
  
  if (halfCasters.includes(classLower)) {
    return halfCasterSlots[level] || [0, 0, 0, 0, 0, 0, 0, 0, 0];
  }
  
  if (classLower === "warlock") {
    return warlockSlots[level] || [0, 0, 0, 0, 0, 0, 0, 0, 0];
  }
  
  return [0, 0, 0, 0, 0, 0, 0, 0, 0];
}

export const SPELLCASTING_CLASSES = [
  "wizard", "sorcerer", "cleric", "druid", "bard", 
  "paladin", "ranger", "warlock"
];

export function isSpellcastingClass(characterClass: string): boolean {
  return SPELLCASTING_CLASSES.includes(characterClass.toLowerCase());
}
